name: Android CI

on:
  pull_request:
    branches: [ "develop_front" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        echo "naver_client_id=${{ secrets.NAVER_CLIENT_ID }}" >> local.properties
        echo "kakao_native_app_key=\"${{ secrets.KAKAO_NATIVE_APP_KEY }}\"" >> local.properties
        echo "kakao_native_app_key_no_quotes=${{ secrets.KAKAO_NATIVE_APP_KEY_NO_QUOTES }}" >> local.properties
        echo "google_login_client_id=\"${{ secrets.GOOGLE_LOGIN_CLIENT_ID }}\"" >> local.properties
        echo "base_url=\"${{ secrets.BASE_URL }}\"" >> local.properties
        echo "re_issue_token=\"${{ secrets.RE_ISSUE_TOKEN }}\"" >> local.properties
        echo "s3_access_key=\"${{ secrets.S3_ACCESS_KEY }}\"" >> local.properties
        echo "s3_secret_key=\"${{ secrets.S3_SECRET_KEY }}\"" >> local.properties
        echo "s3_region=\"${{ secrets.S3_REGION }}\"" >> local.properties
        echo "s3_bucket=\"${{ secrets.S3_BUCKET }}\"" >> local.properties
        echo "kakao_rest_api_key=\"${{ secrets.KAKAO_REST_API_KEY }}\"" >> local.properties
        echo "kakao_url=\"${{ secrets.KAKAO_URL }}\"" >> local.properties
        echo "google_api_key=${{ secrets.GOOGLE_API_KEY }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x ./frontend/ARchive/gradlew

    - name: Build with Gradle
      run: chmod +x ./frontend/ARchive/gradlew
